2018-07-17 21:40:18,479 - teradata.udaexec - INFO - Initializing UdaExec...
2018-07-17 21:40:18,479 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\sngobese\\udaexec.ini: Not Found', 'C:\\Users\\sngobese\\Documents\\Internet_of_Things\\udaexec.ini: Not Found']
2018-07-17 21:40:18,479 - teradata.udaexec - INFO - Found run number file: "C:\Users\sngobese\Documents\Internet_of_Things\.runNumber"
2018-07-17 21:40:18,479 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2018-07-17 21:40:18,479 - teradata.udaexec - INFO - Removed 0 log files.
2018-07-17 21:40:18,580 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\sngobese\Documents\Internet_of_Things\TestAPP.checkpoint
2018-07-17 21:40:18,581 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2018-07-17 21:40:18,581 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: TestAPP
 *          Version: 1.0
 *       Run Number: 20180717214018-8
 *             Host: NB-SNGOBESE
 *         Platform: Windows-10-10.0.16299-SP0
 *          OS User: SNgobese
 *   Python Version: 3.5.2
 *  Python Compiler: MSC v.1900 64 bit (AMD64)
 *     Python Build: ('v3.5.2:4def2a2901a5', 'Jun 25 2016 22:18:55')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: C:\Users\sngobese\AppData\Local\Programs\Python\Python35\lib\site-packages\ipykernel_launcher.py
 *      Working Dir: C:\Users\sngobese\Documents\Internet_of_Things
 *          Log Dir: C:\Users\sngobese\Documents\Internet_of_Things\logs
 *         Log File: C:\Users\sngobese\Documents\Internet_of_Things\logs\TestAPP.20180717214018-8.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\sngobese\\udaexec.ini: Not Found', 'C:\\Users\\sngobese\\Documents\\Internet_of_Things\\udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=TestAPP;Version=1.0;JobID=20180717214018-8;ClientUser=SNgobese;Production=False;udaAppLogFile=C:\Users\sngobese\Documents\Internet_of_Things\logs\TestAPP.20180717214018-8.log;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2018-07-17 21:40:18,582 - teradata.udaexec - INFO - Creating connection: {'password': 'XXXXXX', 'dsn': 'teradata', 'username': 'dbc', 'method': 'odbc'}
2018-07-17 21:40:18,585 - teradata.tdodbc - INFO - Available drivers: SQL Server, SQL Server Native Client 10.0, MySQL ODBC 5.3 ANSI Driver, MySQL ODBC 5.3 Unicode Driver, PostgreSQL ANSI(x64), PostgreSQL Unicode(x64), Amazon Redshift (x64), Teradata Database ODBC Driver 16.20
2018-07-17 21:40:19,931 - teradata.udaexec - INFO - Connection successful. Duration: 1.350 seconds. Details: {'password': 'XXXXXX', 'dsn': 'teradata', 'username': 'dbc', 'method': 'odbc'}
2018-07-17 21:40:34,709 - teradata.udaexec - INFO - Query Successful. Duration: 0.043 seconds, Query: CALL tdata_db_2.Weather_Log_Create(6, 6)
2018-07-17 21:40:36,747 - teradata.udaexec - INFO - Query Successful. Duration: 0.018 seconds, Rows: 2, Query: SELECT * FROM tdata_db_2.Weather_Log ORDER BY Log_Id DESC
2018-07-17 23:09:34,811 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2018-07-17 23:09:34,911 - teradata.udaexec - INFO - UdaExec exiting.
